# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o-QIfVlh-3_EMpK-EYXpH1C673CtMFLS
"""

import pandas as pd

data={
    "Ism":['Muhammadyusuf', 'Zulayho', 'Shukurjon', 'Nigina', 'Shomatjon'],
    'Familiya': ['Zunnunov', 'Qadamova', 'Boqiyev', 'Rustamova', 'Nishonov'],
    'Jinsi': ['erkak', 'ayol', 'erkak', 'ayol', 'erkak'],
    'Yoshi': [21, 28, 21, 26, 22],
    'Manzil': ["Farg'ona", "Farg'ona","Farg'ona", "Andijon", "So'x",],
    'Toifa': [ 'Talaba', "O'qituvchi", 'Talaba', "Oqituvchi", 'Talaba']



}
baza=pd.DataFrame(data)
print(baza)

jinsi=baza[baza['Yoshi']>=25]
print(jinsi)

baza['Yoshi']+=5
print(baza)

baza.to_excel('Baza.xlsx')

df = pd.read_csv('titanic.csv')
df.head(1400)

# print(df.columns)
women = df[df["sex"] == "female"]
print(women.head(1000))

df["sex"].value_counts()

children = df[df["age"] < 18]
print(children.head())

num_children = df[df["age"] < 18].shape[0]
print("18 yoshdan kichik yo'lovchilar soni:", num_children)



person = df[df["ticket"] == "17465"]
print(person)

person = df[df["ticket"] == "112058"]
print(person)

home = df[df['home.dest'] == 'New York, NY']
print(home)